@todo_HostAddress = http://localhost:5077

GET {{todo_HostAddress}}/Todos/
Accept: application/json

###

POST {{todo_HostAddress}}/Todos/
content-type: application/json

{
  "titulo": "Barajando",
    "caducidad": "2025-02-22",
    "completado": false
}
###

POST {{todo_HostAddress}}/manytodos
Content-Type: application/json

[
    { 
        "Titulo": "Salir"
    },
    { 
        "Titulo": "Pasear"
    },
    {
        "Titulo": "Correr"
    }
]

###
PUT {{todo_HostAddress}}/Todos/1
Content-Type: application/json

{   
    "id":1,
    "titulo": "CArlos",
    "completado": true
}

###
DELETE {{todo_HostAddress}}/Todos/1
Content-Type: application/json
